/*
 *  @Author: José Sánchez-Gallego (gallegoj@uw.edu)
 *  @Date: 2022-12-09
 *  @Filename: LogWindowPane.tsx
 *  @License: BSD 3-clause (http://www.opensource.org/licenses/BSD-3-Clause)
 */

import { Grid, Stack } from '@mui/material';
import BooleanOption from 'renderer/Preferences/Components/BooleanOption';
import MenuOption from 'renderer/Preferences/Components/MenuOption';
import Pane from 'renderer/Preferences/Components/Pane';

function NumberLines() {
  const option = 'maxLogMessages';
  const values = [10000, 50000, 100000, 500000, 1000000];

  const title = 'Number of lines';
  const description =
    'Keep this many lines in the log window. Requires an app restart.';

  return (
    <MenuOption
      title={title}
      description={description}
      values={values}
      option={option}
      isNumber
    />
  );
}

export default function LogWindowPane() {
  return (
    <Pane title='Log Window'>
      <Grid container direction='row'>
        <Grid item xs={9}>
          <Stack width='100%' direction='column' spacing={2}>
            <NumberLines />
            <BooleanOption
              title='Save state'
              description='Store the state of each log window when it closes'
              param='log.saveState'
            />
            <BooleanOption
              title='Wrap lines'
              description='Wrap long lines and disable horizontal scrolling'
              param='log.wrap'
            />
            <BooleanOption
              title='Show internal messages'
              description='Show messages generated by HAL internal commands'
              param='log.showInternal'
            />
          </Stack>
        </Grid>
      </Grid>
    </Pane>
  );
}
